"""Add embeddings table and image URLs

Revision ID: a3cab81b0cea
Revises: 46b0feb2f63e
Create Date: 2025-11-20 19:36:01.541721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3cab81b0cea'
down_revision = '46b0feb2f63e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('embedding_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embeddings_entity_id'), 'embeddings', ['entity_id'], unique=False)
    op.create_index(op.f('ix_embeddings_entity_type'), 'embeddings', ['entity_type'], unique=False)
    op.create_index(op.f('ix_embeddings_id'), 'embeddings', ['id'], unique=False)
    op.add_column('recipes', sa.Column('image_thumb_url', sa.String(length=500), nullable=True))
    op.drop_index(op.f('ix_recipes_title'), table_name='recipes')
    op.create_index(op.f('ix_recipes_title'), 'recipes', ['title'], unique=True)
    op.drop_column('recipes', 'embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('embedding', sa.TEXT(), nullable=True))
    op.drop_index(op.f('ix_recipes_title'), table_name='recipes')
    op.create_index(op.f('ix_recipes_title'), 'recipes', ['title'], unique=False)
    op.drop_column('recipes', 'image_thumb_url')
    op.drop_index(op.f('ix_embeddings_id'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_entity_type'), table_name='embeddings')
    op.drop_index(op.f('ix_embeddings_entity_id'), table_name='embeddings')
    op.drop_table('embeddings')
    # ### end Alembic commands ###