"""add_popularity_fields

Revision ID: e4d5cb9f867f
Revises: a3cab81b0cea
Create Date: 2025-12-10 17:32:00.293841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e4d5cb9f867f"
down_revision = "a3cab81b0cea"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recipes", sa.Column("popularity_score", sa.Float(), nullable=True))
    op.add_column("recipes", sa.Column("view_count", sa.Integer(), nullable=True))
    op.add_column("recipes", sa.Column("favorite_count", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipes", "favorite_count")
    op.drop_column("recipes", "view_count")
    op.drop_column("recipes", "popularity_score")
    # ### end Alembic commands ###
